import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';
import nextTypeScript from 'eslint-config-next/typescript';

const config = [
    {
        ignores: [
            'build/**',
            '.next/**',
            'node_modules/**',
            // generated by `lingui compile`
            'src/locales/*/messages.*',
        ],
    },
    ...nextCoreWebVitals,
    ...nextTypeScript,
    {
        rules: {
            'no-unused-vars': 'warn',
            'no-console': 'off',
            'react/react-in-jsx-scope': 'off',
            'react/prop-types': 'off',
            'indent': ['warn', 4, { SwitchCase: 1 }],
            'semi': ['error', 'always'],
        },
    },
];

export default config;
